const products = [
  {
    product_id: "3",
    brand: "Garnier",
    name: "Insight Cosmetics 3-in-1 Primer 30ml",
    images: [
      "https://m.media-amazon.com/images/I/51SIwzWTfoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/51sKHCFycnL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/51K3KIuf73L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61bbfmMZg4L._SL1080_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹275",
    discountPercentage: 20,
    mrp: "₹329",
    rating: 4.2,
    ratingCount: 10473,
    boughtLastMonth: 2000,
    returnPolicy: "Non-Returnable",
    category: "Beauty",
    urls: {
      amazon: "https://amzn.in/d/9h9qI2O",
      flipkart: "https://fktr.in/p8SsegL",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹321",
      flipkart: "₹333",
    },
    problemItSolves: ["Dull skin", "Dark spots", "Uneven skin tone"],
    advantages: [
      "Instantly brightens skin and reduces dark spots",
      "Contains 30X Vitamin C and lemon extracts",
      "Lightweight, non-oily formula",
      "Infused with Niacinamide and Salicylic Acid",
      "Suitable for all skin types",
    ],
    disadvantages: ["Results take time to show", "Non-returnable product"],
    specialFeatures: [
      "Penetrates deeply to target dark spots",
      "Lightweight and non-oily formula",
      "Contains Vitamin C and lemon extracts",
      "Suitable for daily use",
    ],
    includedComponents: ["Face Serum (30 ml)"],
    recommendedUses: [
      "Brightening Skin",
      "Reducing Dark Spots",
      "Evening Skin Tone",
      "Daily Use",
    ],
    itemWeight: "30 Grams",
    countryOfOrigin: "Indonesia",
    manufacturer: "Garnier Skin Naturals",
    productDimensions: "4.5 x 3.7 x 15.2 cm",
    ingredients: [
      "Vitamin C",
      "Niacinamide",
      "Salicylic Acid",
      "Lemon Extracts",
    ],
    usageTips: [
      "Cleanse skin: Use a face wash before applying the serum.",
      "Apply serum: Apply 3-4 drops on your fingertips.",
      "Spread evenly: Spread over the face and neck using gentle tapping motions.",
      "Frequency: Use twice a day, morning and evening, for best results.",
      "Follow up: Follow up with moisturizing creams or sunscreen during the day.",
    ],
  },
  {
    product_id: "2",
    brand: "WishCare",
    name: "WishCare Hair Growth Serum Concentrate",
    images: [
      "https://m.media-amazon.com/images/I/61ntnWS5XTL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/61s+SgsmauL._SY450_.jpg",
      "https://m.media-amazon.com/images/I/61Vuvry4P3L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/5145i9QIjxL._SY450_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹699",
    discountPercentage: 30,
    mrp: "₹999",
    rating: 4.1,
    ratingCount: 5609,
    boughtLastMonth: 30000,
    returnPolicy: "Non-Returnable",
    category: "Beauty",
    urls: {
      amazon: "https://amzn.to/4ijsbWO",
      flipkart: "https://fktr.in/YfUv4UY",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹676",
      flipkart: "₹686",
    },
    problemItSolves: ["Hair loss", "Thinning hair"],
    advantages: [
      "Boosts hair growth with concentrated formula",
      "Reduces hairfall and prolongs hair life cycle",
      "Lightweight leave-on formula with rice water base",
      "Contains powerful ingredients like Redensyl, Anagain, Baicapil, Caffeine, Biotin, and Plant Keratin",
      "Safe and non-toxic ingredients: cruelty-free, paraben-free, vegan, gluten-free, fragrance-free",
    ],
    disadvantages: [
      "Slow results, not for immediate drastic changes",
      "Non-returnable product",
    ],
    specialFeatures: [
      "Micro-spray for direct scalp application",
      "Effective penetration without greasy residue",
      "Formulated with Redensyl, Anagain, Baicapil, Caffeine, Biotin, Keratin, and Rice Water",
      "Clean and non-toxic formulation",
    ],
    includedComponents: [
      "Hair Growth Serum (30 ml)",
      "Micro-spray applicator",
      "User Manual",
    ],
    recommendedUses: [
      "Hair Growth",
      "Hair Fall Control",
      "Thickening Hair",
      "Improving Hair Health",
      "Daily Use",
    ],
    itemWeight: "80 Grams",
    countryOfOrigin: "India",
    manufacturer: "WishCare",
    productDimensions: "3 x 3 x 5 cm",
    ingredients: [
      "Caffeine",
      "Biotin",
      "Plant Keratin",
      "3% Redensyl",
      "4% Anagain",
      "2% Baicapil",
      "Rice Water",
    ],
    usageTips: [
      "Use the micro spray: Apply the serum directly to the affected scalp area.",
      "Massage thoroughly: Use your fingertips to massage the serum into the scalp to ensure even distribution.",
      "Leave overnight: For optimal results, leave the serum on overnight. Consistent use over a three-month period is recommended for noticeable improvements.",
      "Shampoo Pairing: Consider using a gentle, sulfate-free shampoo that promotes hair health to complement the serum's effects.",
      "Diet and Nutrition: Maintain a balanced diet rich in vitamins and minerals essential for hair growth, such as biotin and vitamin E.",
      "Daily Routine: Incorporate the serum into your nightly routine for consistent results.",
      "Visible Results: While some users report seeing baby hairs within a few weeks, optimal results typically require 2-3 months of regular use.",
    ],
  },
  {
    product_id: "1",
    brand: "WishCare",
    name: "Minimalist Sunscreen SPF 50",
    images: [
      "https://m.media-amazon.com/images/I/3158BCnRsLL._SX300_SY300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/61s+SgsmauL._SY450_.jpg",
      "https://m.media-amazon.com/images/I/61Vuvry4P3L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/5145i9QIjxL._SY450_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹399",
    discountPercentage: 50,
    mrp: "₹798",
    rating: 4.1,
    ratingCount: 22319,
    boughtLastMonth: 10000,
    returnPolicy: "Non-Returnable",
    category: "Beauty",
    urls: {
      amazon:
        "https://www.amazon.in/dp/B09FPS9D5T?th=1&linkCode=ll1&tag=3330b5-21&linkId=d684c0ce3a96d3e517c3fdcca343bc01&language=en_IN&ref_=as_li_ss_tl",
      flipkart: "https://fktr.in/txiux55",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹676",
      flipkart: "₹686",
    },
    problemItSolves: ["Hair loss", "Thinning hair"],
    advantages: [
      "Boosts hair growth with concentrated formula",
      "Reduces hairfall and prolongs hair life cycle",
      "Lightweight leave-on formula with rice water base",
      "Contains powerful ingredients like Redensyl, Anagain, Baicapil, Caffeine, Biotin, and Plant Keratin",
      "Safe and non-toxic ingredients: cruelty-free, paraben-free, vegan, gluten-free, fragrance-free",
    ],
    disadvantages: [
      "Slow results, not for immediate drastic changes",
      "Non-returnable product",
    ],
    specialFeatures: [
      "Micro-spray for direct scalp application",
      "Effective penetration without greasy residue",
      "Formulated with Redensyl, Anagain, Baicapil, Caffeine, Biotin, Keratin, and Rice Water",
      "Clean and non-toxic formulation",
    ],
    includedComponents: [
      "Hair Growth Serum (30 ml)",
      "Micro-spray applicator",
      "User Manual",
    ],
    recommendedUses: [
      "Hair Growth",
      "Hair Fall Control",
      "Thickening Hair",
      "Improving Hair Health",
      "Daily Use",
    ],
    itemWeight: "80 Grams",
    countryOfOrigin: "India",
    manufacturer: "WishCare",
    productDimensions: "3 x 3 x 5 cm",
    ingredients: [
      "Caffeine",
      "Biotin",
      "Plant Keratin",
      "3% Redensyl",
      "4% Anagain",
      "2% Baicapil",
      "Rice Water",
    ],
    usageTips: [
      "Use the micro spray: Apply the serum directly to the affected scalp area.",
      "Massage thoroughly: Use your fingertips to massage the serum into the scalp to ensure even distribution.",
      "Leave overnight: For optimal results, leave the serum on overnight. Consistent use over a three-month period is recommended for noticeable improvements.",
      "Shampoo Pairing: Consider using a gentle, sulfate-free shampoo that promotes hair health to complement the serum's effects.",
      "Diet and Nutrition: Maintain a balanced diet rich in vitamins and minerals essential for hair growth, such as biotin and vitamin E.",
      "Daily Routine: Incorporate the serum into your nightly routine for consistent results.",
      "Visible Results: While some users report seeing baby hairs within a few weeks, optimal results typically require 2-3 months of regular use.",
    ],
  },
  {
    product_id: "1",
    brand: "WishCare",
    name: "POND'S Pimple Clear Facewash 100g",
    images: [
      "https://m.media-amazon.com/images/I/51S1xnq72ML._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61s+SgsmauL._SY450_.jpg",
      "https://m.media-amazon.com/images/I/61Vuvry4P3L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/5145i9QIjxL._SY450_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹236",
    discountPercentage: 20,
    mrp: "₹295",
    rating: 4.1,
    ratingCount: 22319,
    boughtLastMonth: 10000,
    returnPolicy: "Non-Returnable",
    category: "Beauty",
    urls: {
      amazon: "https://amzn.in/d/garW8Bh",
      flipkart: "https://fktr.in/42avTYi",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹676",
      flipkart: "₹686",
    },
    problemItSolves: ["Hair loss", "Thinning hair"],
    advantages: [
      "Boosts hair growth with concentrated formula",
      "Reduces hairfall and prolongs hair life cycle",
      "Lightweight leave-on formula with rice water base",
      "Contains powerful ingredients like Redensyl, Anagain, Baicapil, Caffeine, Biotin, and Plant Keratin",
      "Safe and non-toxic ingredients: cruelty-free, paraben-free, vegan, gluten-free, fragrance-free",
    ],
    disadvantages: [
      "Slow results, not for immediate drastic changes",
      "Non-returnable product",
    ],
    specialFeatures: [
      "Micro-spray for direct scalp application",
      "Effective penetration without greasy residue",
      "Formulated with Redensyl, Anagain, Baicapil, Caffeine, Biotin, Keratin, and Rice Water",
      "Clean and non-toxic formulation",
    ],
    includedComponents: [
      "Hair Growth Serum (30 ml)",
      "Micro-spray applicator",
      "User Manual",
    ],
    recommendedUses: [
      "Hair Growth",
      "Hair Fall Control",
      "Thickening Hair",
      "Improving Hair Health",
      "Daily Use",
    ],
    itemWeight: "80 Grams",
    countryOfOrigin: "India",
    manufacturer: "WishCare",
    productDimensions: "3 x 3 x 5 cm",
    ingredients: [
      "Caffeine",
      "Biotin",
      "Plant Keratin",
      "3% Redensyl",
      "4% Anagain",
      "2% Baicapil",
      "Rice Water",
    ],
    usageTips: [
      "Use the micro spray: Apply the serum directly to the affected scalp area.",
      "Massage thoroughly: Use your fingertips to massage the serum into the scalp to ensure even distribution.",
      "Leave overnight: For optimal results, leave the serum on overnight. Consistent use over a three-month period is recommended for noticeable improvements.",
      "Shampoo Pairing: Consider using a gentle, sulfate-free shampoo that promotes hair health to complement the serum's effects.",
      "Diet and Nutrition: Maintain a balanced diet rich in vitamins and minerals essential for hair growth, such as biotin and vitamin E.",
      "Daily Routine: Incorporate the serum into your nightly routine for consistent results.",
      "Visible Results: While some users report seeing baby hairs within a few weeks, optimal results typically require 2-3 months of regular use.",
    ],
  },
  {
    product_id: "3",
    brand: "Garnier",
    name: "NutriPro Juicer Mixer Grinder (500W, 2 Jars)",
    images: [
      "https://m.media-amazon.com/images/I/71PkRff5mdL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/51sKHCFycnL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/51K3KIuf73L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61bbfmMZg4L._SL1080_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹1599",
    discountPercentage: 68,
    mrp: "₹5000",
    rating: 4.2,
    ratingCount: 18976,
    boughtLastMonth: 8000,
    returnPolicy: "Non-Returnable",
    category: "Kitchen",
    urls: {
      amazon: "https://amzn.to/4kGhQ8X",
      flipkart: "https://fktr.in/HpqSnv4",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹321",
      flipkart: "₹333",
    },
  },
  {
    product_id: "3",
    brand: "Garnier",
    name: "Vasukie 2-in-1 Olive Oil Sprayer (500ml)",
    images: [
      "https://m.media-amazon.com/images/I/611MG2OBsyL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/51sKHCFycnL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/51K3KIuf73L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61bbfmMZg4L._SL1080_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹197",
    discountPercentage: 67,
    mrp: "₹599",
    rating: 4.2,
    ratingCount: 176,
    boughtLastMonth: 3000,
    returnPolicy: "Non-Returnable",
    category: "Kitchen",
    urls: {
      amazon: "https://amzn.to/4hmlK3Z",
      flipkart: "https://fktr.in/vqko7AA",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹321",
      flipkart: "₹333",
    },
  },
  {
    product_id: "3",
    brand: "Garnier",
    name: "Pigeon Mini Handy Chopper (400ml, Green)",
    images: [
      "https://m.media-amazon.com/images/I/51RXzjrUmkL._SX569_.jpg",
      "https://m.media-amazon.com/images/I/51sKHCFycnL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/51K3KIuf73L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61bbfmMZg4L._SL1080_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹198",
    discountPercentage: 64,
    mrp: "₹545",
    rating: 4.2,
    ratingCount: 275130,
    boughtLastMonth: 10000,
    returnPolicy: "Non-Returnable",
    category: "Kitchen",
    urls: {
      amazon: "https://amzn.to/3RiakU4",
      flipkart: "https://fktr.in/ALwWMEr",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹321",
      flipkart: "₹333",
    },
  },
  {
    product_id: "3",
    brand: "Garnier",
    name: "ATOM Digital Kitchen Weighing Scale (10Kg, SF400/A121)",
    images: [
      "https://m.media-amazon.com/images/I/71775fRr+gL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/51sKHCFycnL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/51K3KIuf73L._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61bbfmMZg4L._SL1080_.jpg",
    ],
    warranty: "No warranty",
    currentPrice: "₹205",
    discountPercentage: 66,
    mrp: "₹545",
    rating: 4.2,
    ratingCount: 275130,
    boughtLastMonth: 30000,
    returnPolicy: "Non-Returnable",
    category: "Kitchen",
    urls: {
      amazon: "https://amzn.to/4kzPWv7",
      flipkart: "https://fktr.in/M1Y0nLK",
      youtube: "https://youtube.com/shorts/Wo4i7-MsZR4?si=nOhJ_GYdypldiEIL",
    },
    prices: {
      amazon: "₹321",
      flipkart: "₹333",
    },
  },
];

export default products;
